####################   德一智慧城市Podfile模板   ####################

source 'https://github.com/CocoaPods/Specs.git'
source 'http://192.168.120.208/iOS_Group/DYSpecs.git'

use_frameworks!

platform :ios, '10.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'



  pod 'DYNetwork', :git => 'http://git.zhcs.com/iOS_Group/DYNetwork.git'
  pod 'DYService', :git => 'http://git.zhcs.com/iOS_Group/DYService.git'
  pod 'DYSuperKit', :git => 'http://git.zhcs.com/iOS_Group/DYKit.git'
  pod 'DYFoundation', :git => 'http://git.zhcs.com/iOS_Group/DYFoundation.git'
  pod 'DYResources', :git => 'http://git.zhcs.com/iOS_Group/DYResources.git'



  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
